"""agregar usuario_id a vehiculos

Revision ID: cce103579cb2
Revises: c66722d21f58
Create Date: 2026-07-18 16:50:01.967217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce103579cb2'
down_revision: Union[str, Sequence[str], None] = 'c66722d21f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehiculos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehiculos', type_='foreignkey')
    op.drop_column('vehiculos', 'usuario_id')
    # ### end Alembic commands ###
