"""crear tabla mantenimientos

Revision ID: f117d774af0d
Revises: cce103579cb2
Create Date: 2026-07-18 17:33:36.457684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f117d774af0d'
down_revision: Union[str, Sequence[str], None] = 'cce103579cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CAMBIO_ACEITE', 'DISTRIBUCION', 'NEUMATICOS', 'FRENOS', 'BATERIA', 'SERVICE_GENERAL', 'OTRO', name='tipomantenimiento'), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_id'), 'mantenimientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mantenimientos_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    # ### end Alembic commands ###
